### ISSUE TITLE
Feature request: include characteristic data type

### ISSUE THREAD

**Issue by ebaauw** [NordicSemiconductor/bluetooth-numbers-database#53]
I appreciate this initiative, and would love to use (and maybe even contribute) to it.

I started out with whitelisting the UUIDs exposed by the device I'm trying to support, and hate to maintain that list myself, even if it is "just five minutes" work.  However, I need to know the data type of the characteristic, in order to interpret its value.  I suppose, I could use the `indentifer` attribute to get the definition from `https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Characteristics/`_identifier_`.xml`, parse the XML to extract the `Format`, probably ignoring characteristics with multiple `Field` entries for now, but that will take me a bit longer than five minutes.  So I would likely end up maintaining my own list after all.

Would it be possible to add the data type?  I suppose more users of this database will run into a similar issue.

**Comment by philips77** [comment]
Hello,
The data types are very complex in some cases, with flags that add or remove some other fields. It should be done properly and it's not really a priority. Usually, apps are designed to use some data format that's used by their devices and they don't care about other formats. It's only for generic apps like nRF Connect or other that that would be useful. Also, the XMLs you pointed to above are no longer published, as far as I know. Now the single source of truth is a PDF file. I imagine this PDF file is generated form some standard form, which could be released as well to make automation easier, but I'm not aware of such.

So we could start with a very simple types, like UTF-8 or numbers, but I'm afraid that would lead to questions and misunderstanding and requests for more. But it's definitely a good place to start. We're missing such format database ourselves.

**Comment by ebaauw** [comment]
I appreciate the data type complexity.  I think, indeed, it's good to start with the simple types.

> Usually, apps are designed to use some data format that's used by their devices and they don't care about other formats.

Which basically translates to: spending the "just five minutes" work to maintain your own whitelist.

> Also, the XMLs you pointed to above are no longer published, as far as I know.

I wrote a little programme (as yet unpublished) to match the identifiers in this database against the `.xml` files on `bluetooth.com`.  After some corrections (see PR #54), I only miss three descriptors and four characteristics.  I'm pleasantly surprised that the site didn't block my requests while testing the programme ;-)

Next, I want to try parsing the definitions, extracting the characteristic data types.  I adopted the SOAP/XML parser for my Homebridge plugin for Sonos to convert the XML definitions to JavaScript objects.

**Comment by philips77** [comment]
> it's good to start with the simple types

Even the simple types are more difficult than one would think. This is what GSS in chapter 2.1 (https://www.bluetooth.com/specifications/specs/ -> GATT Specification Supplement) says about a Scalar Value:

> When a characteristic field represents a scalar value and unless otherwise specified by the characteristic 
definition, the represented value is related to the raw value by the following equations, where the M 
coefficient, d, and b exponents are defined per field of characteristic:
R = C * M * 10^d * 2^b
Where:
R = represented value
C = raw value
M = multiplier, positive or negative integer (between -10 and +10)
d = decimal exponent, positive or negative integer
b = binary exponent, positive or negative integer
The default values are: M = 1, d = 0 and b = 0

Additionally, there's unit and description how to display a value, e.g. 4*10^-1 m can be shown as 40 cm, 0.4 m, 0.4 meter, etc. The exponent or unit not always correspond to most human readable format.

Regarding the XML files, there is no guarantee that they won't change, or won't be removed. Currently the single source of truth is the PDF I linked above and the website doesn't even point to the old descriptions or XMLs. The characteristics adopted recently don't even have XMLs and are not in our database yet, vide Content Control ID (chapter 3.45). 

Even one of the oldest, and simples of the complex characteristics like HRM (https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Characteristics/org.bluetooth.characteristic.heart_rate_measurement.xml) adds additional info as a comment (that multiple RR-interval fields may be added at the end), meaning that even the "standard" XML schema can't handle all possible variations.

> Which basically translates to: spending the "just five minutes" work to maintain your own whitelist.

Yes, that is assuming every characteristic has an owner. Also, to understand a schema, create an XML, check it, validate and create a PR is this kind of 5 minutes that ends up being 2 days.

**Comment by philips77** [comment]
I'm not saying it shouldn't be done, or can't be done, but this is a huge task. That's why it hasn't been done yet, and even Bluetooth SIG has withdrawn their XMLs as too difficult to maintain.

**Comment by ebaauw** [comment]
Somehow, that tends to happen when XML is involved ;-)

I’ll close this issue for now, but I’ll be happy to help where I can.  “Even a journey of 10,000 miles starts with the first step”…
