### ISSUE TITLE
BLE

### ISSUE THREAD

**Issue by kyleyelton24** [NordicSemiconductor/bluetooth-numbers-database#58]

**Comment by dploveME** [comment]
![image](https://user-images.githubusercontent.com/89214758/130229990-d9326bad-76bf-4954-b7f1-b21782873938.png)

**Comment by dinesharjani** [comment]
@dploveME  can you post this in https://github.com/NordicSemiconductor/IOS-nRF-Connect and also provide a sequence of steps to replicate?
