### ISSUE TITLE
Missing uuids from core specification

### ISSUE THREAD

**Issue by doggkruse** [NordicSemiconductor/bluetooth-numbers-database#77]
There seem to be several uuids missing from the core specification.  For example, Server Supported Features (0x2b3a) is nowhere to be found.  Are these uuids periodically updated from the latest core spec?

**Comment by dinesharjani** [comment]
I mean, that's the idea, but it's human-operated not computer-operated.

I'll try to go through the spec later today and see if there are more Attributes missing. Thanks!

**Comment by dinesharjani** [comment]
See https://github.com/NordicSemiconductor/bluetooth-numbers-database/pull/80
